export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories/pizza.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories/hamburger.png"),
  },
  {
    id: 3,
    name: "Spagetti",
    image: require("../assets/images/categories/spaghetti.png"),
  },
  {
    id: 4,
    name: "Thali",
    image: require("../assets/images/categories/takeout-box.png"),
  },
  {
    id: 5,
    name: "Drinks",
    image: require("../assets/images/categories/tropical-drink.png"),
  },
  {
    id: 6,
    name: "Cupcake",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 7,
    name: "Fish",
    image: require("../assets/images/categories/tropical-fish.png"),
  },
];

export const restaurants = [
  {
    id: 1,
    name: "Papa Johns",
    image: require("../assets/images/restaurants/papa-john.jpg"),
    descriptions: "Hot and spicy pizza",
    lng: 38.214602,
    lat: -85.5324269,
    address: "434 seconda street",
    rating: 4,
    reviews: "4.4k",
    category: "Pizza",
    dishes: [
      {
        id: 1,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 2,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 3,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 4,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 5,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 6,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 7,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 8,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 9,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
    ],
  },
  {
    id: 2,
    name: "Chowman",
    image: require("../assets/images/restaurants/chowman.jpg"),
    descriptions: "Hot and spicy pizza",
    lng: 38.214602,
    lat: -85.5324269,
    address: "434 seconda street",
    rating: 4,
    reviews: "4.4k",
    category: "Pizza",
    dishes: [
      {
        id: 1,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 2,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 3,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 4,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 5,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 6,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 7,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
    ],
  },
  {
    id: 3,
    name: "Papa Johns",
    image: require("../assets/images/restaurants/papa-john.jpg"),
    descriptions: "Hot and spicy pizza",
    lng: 38.214602,
    lat: -85.5324269,
    address: "434 seconda street",
    rating: 4,
    reviews: "4.4k",
    category: "Pizza",
    dishes: [
      {
        id: 1,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 2,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 3,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 4,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 5,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 6,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 7,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
    ],
  },
  {
    id: 4,
    name: "Chowman",
    image: require("../assets/images/restaurants/chowman.jpg"),
    descriptions: "Hot and spicy pizza",
    lng: 38.214602,
    lat: -85.5324269,
    address: "434 seconda street",
    rating: 4,
    reviews: "4.4k",
    category: "Pizza",
    dishes: [
      {
        id: 1,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 2,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 3,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 4,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 5,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 6,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 7,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
    ],
  },
  {
    id: 5,
    name: "Papa Johns",
    image: require("../assets/images/restaurants/papa-john.jpg"),
    descriptions: "Hot and spicy pizza",
    lng: 38.214602,
    lat: -85.5324269,
    address: "434 seconda street",
    rating: 4,
    reviews: "4.4k",
    category: "Pizza",
    dishes: [
      {
        id: 1,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 2,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 3,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 4,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 5,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 6,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 7,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
    ],
  },
  {
    id: 6,
    name: "Chowman",
    image: require("../assets/images/restaurants/chowman.jpg"),
    descriptions: "Hot and spicy pizza",
    lng: 38.214602,
    lat: -85.5324269,
    address: "434 seconda street",
    rating: 4,
    reviews: "4.4k",
    category: "Pizza",
    dishes: [
      {
        id: 1,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 2,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 3,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 4,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 5,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 6,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
      {
        id: 7,
        name: "pizza",
        description: "cheesy garlic pizza",
        price: 10,
        image: require("../assets/images/dishes/pizza.jpeg"),
      },
    ],
  },
];
